name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y build-essential checkinstall

      - name: Сборка ПО
        run: make
        
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y build-essential checkinstall

      - name: Сборка ПО
        run: make
        
      - name: Запуск тестов
        run: ./cicd/test.sh
        
  package:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y build-essential checkinstall

      - name: Сборка ПО
        run: make

      - name: Сборка .deb пакета
        run: |
          sudo checkinstall \
            --pkgname=bubble_sort \
            --pkgversion=1.0 \
            --pkggroup=utils \
            --install=no \
            -y \
            make install

      - name: Сохранение артефакта
        uses: actions/upload-artifact@v4
        with:
          name: bubble_sort_package
          path: ./bubble-sort_*.deb  # Автоматическое совпадение с именем пакета
  
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bubble_sort_package
          path: artifacts/

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag Docker image
        run: |
          DOCKERHUB_USER="${{ secrets.DOCKER_USERNAME }}"
          docker buildx build \
          --tag $DOCKERHUB_USER/bubble-sort:latest \
          --push \
          ./artifacts

      - name: Запуск контейнера
        run: |
          echo -e "5\n50\n40\n30\n20\n10" | docker run -i --rm ${{ secrets.DOCKER_USERNAME }}/bubble-sort:latest